### ISSUE TITLE
Need to make more enemies to fight in the dungeons.

### ISSUE THREAD

**Issue by Koofus** [Koofus/Mysteries-of-Galoo#15]
Look at the encounters.py to get an idea on what I'm talking about.

**Comment by mminer4** [comment]
Are you sure you meant map_creator.py? I looked there and couldn't find anything with the word troll. I did enemies in encounters.py. Is that what you meant?

**Comment by Koofus** [comment]
I meant encounters.py instead of map creator.py

**Comment by Koofus** [comment]
I meant encounters.py instead of map creator.py
