### ISSUE TITLE
Player moves into invalid map block.

### ISSUE THREAD

**Issue by awhited** [Koofus/Mysteries-of-Galoo#6]
When in game, when you try to move into a '0' block, a message is shown to pick another block and the player doesn't seem to move. If you repeat many times (more than 6), 'Player' appears in the row above and then crashes the game.

**Comment by Koofus** [comment]
if next_location != empty, zero, dungeon then return current location

that should solve that problem LOL I knew that would happen I just was working on better stuff at the time.

**Comment by Koofus** [comment]
ill fix that

**Comment by Koofus** [comment]
Ya still didn't fix this yet
